=encoding utf8

[[Mojolicious API リファレンス]]

=head1 名前

  Usage: APPLICATION inflate [OPTIONS]

    ./myapp.pl inflate

  Options:
    -h, --help          Show this summary of available options
        --home <path>   Path to home directory of your application, defaults to
                        the value of MOJO_HOME or auto-detection
    -m, --mode <name>   Operating mode for your application, defaults to the
                        value of MOJO_MODE/PLACK_ENV or "development"

=head1 使い方

  Usage: APPLICATION inflate

=head1 説明

[[Mojolicious::Command::Author::inflate]]はアプリケーションのC<DATA>セクションに埋め込まれた
テンプレートと静的ファイルを本当のファイルに出力します。

これはコアのコマンドです。いつでも有効になっていて、 これをフォークして新しいコマンドの構築を学ぶための、よいサンプルになっています。

デフォルトで利用可能なコマンドの一覧については[[Mojolicious::Commands]]のC<コマンド>の項目をみてください。

=head1 属性

[[Mojolicious::Command::Author::inflate]]は
[[Mojo::Command]]からすべての属性を継承しており、
次の新しい属性を実装しています。

=head2 description

  my $description = $inflate->description;
  $inflate        = $inflate->description('Foo');

このコマンドの短い説明。コマンドの一覧表示に利用されます。

=head2 usage

  my $usage = $inflate->usage;
  $inflate  = $inflate->usage('Foo');

このコマンドの使用方法の情報。ヘルプの表示に利用されます。

=head1 メソッド

[[Mojolicious::Command::Author::inflate]]はL<Mojo::Command>からすべてのメソッドを継承しており、
次の新しいメソッドを実装しています。

=head2 run

  $inflate = $inflate->run(@ARGV);

このコマンドを実行します。

=head1 参考

L<Mojolicious>, L<Mojolicious::Guides>, L<http://mojolicio.us>.

(Mojolicious 6.05を反映)

=cut