=encoding utf8

[[Mojolicious API リファレンス|mojo-api-reference]]

=head1 名前

Mojo - Web開発のツールキット

=head1 使い方

  # HTTP/WebSocketユーザーエージェント
  use Mojo::UserAgent;
  my $ua = Mojo::UserAgent->new;
  say $ua->get('www.mojolicious.org')->result->headers->server;

  # CSSセレクタつきのHTML/XML DOMパーサー
  use Mojo::DOM;
  my $dom = Mojo::DOM->new('<div><b>Hello Mojo!</b></div>');
  say $dom->at('div > b')->text;

  # Perl風のテンプレート
  use Mojo::Template;
  my $mt = Mojo::Template->new(vars => 1);
  say $mt->render('Hello <%= $what %>!', {what => 'Mojo'});

  # HTTP/WebSocketサーバー
  use Mojo::Server::Daemon;
  my $daemon = Mojo::Server::Daemon->new(listen => ['http://*:8080']);
  $daemon->unsubscribe('request')->on(request => sub {
    my ($daemon, $tx) = @_;
    $tx->res->code(200);
    $tx->res->body('Hello Mojo!');
    $tx->resume;
  });
  $daemon->run;

  # イベントループ
  use Mojo::IOLoop;
  for my $seconds (1 .. 5) {
    Mojo::IOLoop->timer($seconds => sub { say $seconds });
  }
  Mojo::IOLoop->start;

=head1 説明

パワフルなWeb開発のツールキット。簡単なWebアプリケーションと、[[Mojolicious]]のようなさらにハイレベルなWebフレームワークを書くために必要な、すべての基本的なツールとヘルパーを持っています。

PerlのリアルタイムWebフレームワークのための柔軟な実行環境。簡単なWebアプリケーションと[[Mojolicious]]のような高いレベルのWebフレームワークを書くための機能がそろっています。もっとも一般的に利用されるツールは、[[Mojo::UserAgent]],
[[Mojo::DOM]],、[[Mojo::JSON]]、 [[Mojo::Server::Daemon]]、 [[Mojo::Server::Prefork]],
[[Mojo::IOLoop]]、[[Mojo::Template]]などです。

もっとよく知りたいなら[[Mojolicious::Guides]]を見てください。

(v8.12 2019/03/11更新)
