=encoding utf8

B<このモジュールは削除されました。>

[[Mojolicious API リファレンス]]

=head1 名前

Mojolicious::Command::Generate::Hypnotoad - Hypnotoad生成コマンド

=head1 使い方

  use Mojolicious::Command::Generate::Hypnotoad;

  my $hypnotoad = Mojolicious::Command::Generate::Hypnotoad->new;
  $hypnotoad->run(@ARGV);

=head1 説明

[[Mojolicious::Command::Generate::Hypnotoad]]はC<hypnotoad.conf>
のジェネレーターです。

=head1 属性

L<Mojolicious::Command::Generate::Hypnotoad>は
L<Mojo::Command>からすべての属性を継承しており、
次の新しい属性を実装しています。

=head2 description

  my $description = $hypnotoad->description;
  $hypnotoad      = $hypnotoad->description('Foo!');

このコマンドの短い説明。コマンドの一覧表示に利用されます。

=head2 usage

  my $usage  = $hypnotoad->usage;
  $hypnotoad = $hypnotoad->usage('Foo!');

このコマンドの使用方法の情報。ヘルプの表示に利用されます。

=head1 メソッド

[[Mojolicious::Command::Generate::Hypnotoad]]は
[[Mojo::Command]]からすべてのメソッドを継承しており、
次の新しいメソッドを実装しています。

=head2 run

  $hypnotoad = $hypnotoad->run(@ARGV);

このコマンドを実行します。

=head1 参考

L<Mojolicious>, L<Mojolicious::Guides>, L<http://mojolicio.us>.

(2012/6/5更新)

=cut
