=encoding utf8

B<このプラグインは削除されました>

[[Mojolicious API リファレンス|mojo-api-reference]]



=head1 名前

Mojolicious::Plugin::PoweredBy - Powered Byプラグイン

=head1 使い方

  # Mojolicious
  $self->plugin('PoweredBy');
  $self->plugin(PoweredBy => (name => 'MyApp 1.0'));

  # Mojolicious::Lite
  plugin 'PoweredBy';
  plugin PoweredBy => (name => 'MyApp 1.0');

=head1 説明

[[Mojolicious::Plugin::PoweredBy]]は、C<X-Powered-By>ヘッダを追加するプラグインであり、デフォルト値はC<Mojolicious (Perl)>です。
これはコアプラグインなので、いつでも使用可能であり、新しいプラグインを作成する方法を学ぶための良いコード例になります。

=head1 オプション

=head2 powered_by

  plugin PoweredBy => (name => 'MyApp 1.0');

C<X-Powered-By>ヘッダの値。

=head1 メソッド

[[Mojolicious::Plugin::PoweredBy]]は、[[Mojolicious::Plugin]]のすべてのメソッドを継承し、以下の新しいメソッドを実装しています。

=head2 register

  $plugin->register;

[[Mojolicious]]アプリケーションに、プラグインのフックを登録します。

=head1 参考

L<Mojolicious>, L<Mojolicious::Guides>, L<http://mojolicio.us>.

(2012/6/7更新)

=cut
